version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: form-builder-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: formbuilder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - form-builder-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: form-builder-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/formbuilder
      PORT: 4000
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - form-builder-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: form-builder-frontend
    environment:
      VITE_API_URL: http://localhost:4000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - form-builder-network

volumes:
  postgres_data:

networks:
  form-builder-network:
    driver: bridge
